# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Quintus Sertorius
name: "QuintusSertorius"
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  My journey towards financial and spiritual freedom. Here you will find posts about
  self-improvement, discipline, philosophy, online business, financial markets and whole lot of
  other things.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://quintus-sertorius-blue.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: BlueSertorius

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
minimal_mistakes_skin: "contrast "
repository: quintus-sertorius-blue/QuintusSertorius.github.io
github: [metadata]
search: true
include: [ "_pages", "images" ]

paginate: 5 # amount of posts to show
paginate_path: /page:num/

author:
  name: "Quintus Sertorius"
  avatar: "/images/quinto.jpg"
  bio: "Copywriting, wellness and self-improvement. ANCR."
  location: "Rome 90 B.C."
  links:
    - label: "Ebook"
      icon: "fas fa-fw fa-book"
      url: "https://quintus-sertorius-blue.github.io/BlueSertorius/ebook/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/BlueSertorius"
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/BlueSertorius"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

teaser: "/images/sertorius.jpg"
og_image: "/images/biblio.jpg"

comments:
  provider: "disqus"
  disqus:
    shortname: "quintusertorius"

search: true

twitter:
  username: "BlueSertorius"



# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
